# Generated by Django 5.2.6 on 2025-09-16 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_remove_produto_usuario_produto_loja_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='data_criacao',
            new_name='data_cadastro',
        ),
        migrations.AddField(
            model_name='cliente',
            name='total_compras',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='gestao.loja'),
        ),
    ]
