# Generated by Django 5.2.6 on 2025-09-16 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_rename_data_criacao_cliente_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='loja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestao.loja'),
        ),
    ]
