# Generated by Django 5.2.6 on 2025-09-17 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0007_fornecedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='usuario',
        ),
        migrations.AddField(
            model_name='venda',
            name='loja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='gestao.loja'),
        ),
        migrations.AddField(
            model_name='venda',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='venda',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas_produto', to='gestao.produto'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
    ]
