# Generated by Django 5.2.6 on 2025-09-22 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0010_remove_produto_preco_produto_preco_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendas_cliente', to='gestao.cliente'),
        ),
    ]
