# Generated by Django 5.2.6 on 2025-09-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0012_alter_venda_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
