# Generated by Django 5.2.6 on 2025-09-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0013_loja_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Espécie'), ('pix', 'PIX'), ('debito', 'Débito'), ('credtio_avista', 'Crédito à vista'), ('credito_parcelado', 'Crédito Parcelado')], default='dinheiro', max_length=20),
        ),
        migrations.AddField(
            model_name='venda',
            name='parcelas',
            field=models.IntegerField(default=1),
        ),
    ]
