# Generated by Django 5.2.6 on 2025-10-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0014_venda_desconto_venda_forma_pagamento_venda_parcelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.CharField(default='Vazio', max_length=100),
        ),
    ]
